/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'dark-bg': '#0a0f1e',
        'dark-card': '#111827',
        'dark-text': '#f9fafb',
        'dark-muted': '#6b7280',
        'accent-blue': '#3b82f6',
        'accent-green': '#10b981',
        'accent-amber': '#f59e0b',
        'accent-red': '#ef4444',
        
        "surface-container-highest": "#2d3449",
        "secondary-container": "#3f4759",
        "on-surface": "#dae2fd",
        "inverse-surface": "#dae2fd",
        "secondary-fixed": "#dbe2f9",
        "on-background": "#dae2fd",
        "on-primary-container": "#e2f6ff",
        "tertiary-container": "#c34400",
        "error": "#ffb4ab",
        "surface-dim": "#0b1326",
        "tertiary-fixed": "#ffdbce",
        "surface-tint": "#4cd6ff",
        "primary-fixed-dim": "#4cd6ff",
        "on-tertiary-container": "#fff0eb",
        "surface-container-lowest": "#060e20",
        "secondary": "#bfc6dc",
        "on-primary": "#003543",
        "secondary-fixed-dim": "#bfc6dc",
        "tertiary-fixed-dim": "#ffb59a",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#370e00",
        "on-secondary-fixed": "#141b2c",
        "on-surface-variant": "#c2c6d9",
        "outline-variant": "#424656",
        "on-tertiary": "#5a1b00",
        "surface-variant": "#2d3449",
        "primary-fixed": "#b7eaff",
        "inverse-primary": "#00677f",
        "on-secondary-fixed-variant": "#3f4759",
        "inverse-on-surface": "#283044",
        "error-container": "#93000a",
        "primary": "#4cd6ff",
        "surface-container-high": "#222a3d",
        "primary-container": "#007994",
        "surface-container-low": "#131b2e",
        "background": "#0b1326",
        "tertiary": "#ffb59a",
        "on-primary-fixed": "#001f28",
        "on-error": "#690005",
        "on-secondary-container": "#adb5ca",
        "outline": "#8c90a2",
        "surface-bright": "#31394d",
        "on-secondary": "#293041",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#802a00",
        "on-primary-fixed-variant": "#004e60",
        "surface": "#0b1326"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
